/*7. Sales leadership wants performance rolled up the org chart. For every employee,
compute the total completed order value generated by their whole team — that is,
themselves plus everyone reporting under them at any depth. A Sales Rep's team is just
themselves; a manager's is their entire subtree. Required output: employee_id,
employee_name, role, team_total_revenue.*/

WITH org_subtree AS (
    SELECT
        employee_id AS root_employee_id,     -- the manager/rep we're rolling up FOR
        employee_id AS member_employee_id,   -- a person counted IN that roll-up
        0 AS depth
    FROM dim_employee

    UNION ALL

    SELECT
        ot.root_employee_id,     -- root stays fixed as we go deeper
        e.employee_id AS member_employee_id,
        ot.depth + 1 AS depth
    FROM org_subtree AS ot
    JOIN dim_employee AS e
        ON e.manager_id = ot.member_employee_id
),

team_revenue AS (
    -- ---------- ROLL UP REVENUE PER ROOT ----------
    SELECT
        ot.root_employee_id,
        COALESCE(SUM(fo.order_total), 0) AS team_total_revenue
    FROM org_subtree AS ot
    LEFT JOIN fact_orders AS fo
        ON fo.sales_rep_id = ot.member_employee_id
        AND fo.order_status = 'Completed'
    GROUP BY ot.root_employee_id
)

-- ---------- FINAL OUTPUT ----------
SELECT
    e.employee_id,
    e.employee_name,
    e.role,
    tr.team_total_revenue
FROM team_revenue AS tr
JOIN dim_employee AS e
    ON e.employee_id = tr.root_employee_id
ORDER BY tr.team_total_revenue DESC
OPTION (MAXRECURSION 100);